// hash: #f094138a
// @formatter:off

package me.wietlol.wietbot.data.messages.models.serializers

import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import me.wietlol.bitblock.api.serialization.DeserializationContext
import me.wietlol.bitblock.api.serialization.ModelSerializer
import me.wietlol.bitblock.api.serialization.Schema
import me.wietlol.bitblock.api.serialization.SerializationContext
import me.wietlol.bitblock.api.serialization.deserialize
import me.wietlol.utils.common.streams.readUnsignedVarInt
import me.wietlol.utils.common.streams.writeUnsignedVarInt
import me.wietlol.wietbot.data.messages.models.builders.InlineMonospacedPartBuilder
import me.wietlol.wietbot.data.messages.models.models.*
import me.wietlol.wietbot.data.messages.models.models.InlineMonospacedPart

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object InlineMonospacedPartSerializer : ModelSerializer<InlineMonospacedPart, InlineMonospacedPart>
{
	private val endOfObject: Int = 0
	
	private val textIndex: Int = 1
	
	override val modelId: UUID
		get() = InlineMonospacedPart.serializationKey
	
	override val dataClass: Class<InlineMonospacedPart>
		get() = InlineMonospacedPart::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: InlineMonospacedPart)
	{
		stream.writeUnsignedVarInt(textIndex)
		schema.serialize(serializationContext, stream, entity.text)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): InlineMonospacedPart
	{
		var text: String? = null
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultInlineMonospacedPart(
					text!!,
				)
				textIndex -> text = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
