// hash: #54c92203
// @formatter:off

package me.wietlol.wietbot.data.messages.models.models

import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface MessageEvent : BitSerializable, ChatEvent, Jsonable
{
	val content: Content
	
	override fun duplicate(): MessageEvent
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
