// hash: #e616c84f
// data: serializationKey:8c542b3a-6e79-469e-ba05-87365498035b
// @formatter:off

package me.wietlol.wietbot.data.messages.models.models

import java.util.UUID
import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable
import me.wietlol.utils.common.emptyHashCode
import me.wietlol.utils.common.toJsonString
import me.wietlol.utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface MultiPart : BitSerializable, ContentPart, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("serializationKey")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val parts: List<ContentPart>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is MultiPart) return false
		
		if (parts != other.parts) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(parts)
	
	override fun toJson(): String =
		"""{"parts":${parts.toJsonString()}}"""
	
	override fun duplicate(): MultiPart
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
