// hash: #f8500e81
// @formatter:off

package me.wietlol.wietbot.data.messages.models.builders

import me.wietlol.wietbot.data.messages.models.models.*
import me.wietlol.wietbot.data.messages.models.models.DefaultBoldPart

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class BoldPartBuilder
{
	var inner: ContentPart? = null
	
	fun build(): BoldPart =
		DefaultBoldPart(
			inner!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
