// hash: #0b774063
// @formatter:off

package me.wietlol.wietbot.data.messages.models.builders

import me.wietlol.wietbot.data.messages.models.models.*
import me.wietlol.wietbot.data.messages.models.models.DefaultContent

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class ContentBuilder
{
	var part: ContentPart? = null
	
	fun build(): Content =
		DefaultContent(
			part!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
