// hash: #da9f2687
// @formatter:off

package me.wietlol.wietbot.data.messages.models.builders

import me.wietlol.wietbot.data.messages.models.models.*
import me.wietlol.wietbot.data.messages.models.models.DefaultStrikeoutPart

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class StrikeoutPartBuilder
{
	var inner: ContentPart? = null
	
	fun build(): StrikeoutPart =
		DefaultStrikeoutPart(
			inner!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
